# Generated by Django 4.2 on 2023-09-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_uploadedimage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
