# Generated by Django 4.2 on 2023-09-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_uploadedimage_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
