# Generated by Django 4.2 on 2023-09-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_uploadedimage_pincode_alter_uploadedimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadCattleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.IntegerField(blank=True, max_length=6, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
